### PR TITLE
changes related to new MTL metadata table

### PR DESCRIPTION
**Pull request by daveoloughlin**
Attached is the definition of the new MTL metadata table.
[tableCreate.txt](https://github.com/nemac/landsatfact-data/files/284419/tableCreate.txt)

### CODE REVIEW

**Comment by daveism** [comment]
Updated production database with changes.  and updated sql repo https://github.com/nemac/landsatfact-sql.   https://github.com/nemac/landsatfact-sql/blob/master/functions/keys_and_values.sql

also need to update https://github.com/nemac/landsatfact-sql/blob/master/functions.md#function-keys_and_values

**Comment by daveism** [comment]
running a test custom request in dev

**Comment by daveoloughlin** [comment]
Also added a function to wrap the addition or a level1_metadata row and the insertion of its key in landsat_metadata.
[keysAndValuesSQL.txt](https://github.com/nemac/landsatfact-data/files/284472/keysAndValuesSQL.txt)
The code changes consist of:
landsatFactTools.py:
The addition of readAndWriteQuadCC function to reading and writing of quad cloud cover info. This function makes it easier to notice failures that we fear are happening.
Updates to the postgresCommand to allow the return of rowcount which indicates the success or failure of updates and deletes.
The addition of a sendEmail function for notifiying developers of LCV problems. Calls email.php with error text.
rasterAnalysis_GDAL.py:
Changed the mtlData class to read and write the information in MTL.txt file to/from the level1_metadata table.
The sensorBand class was changed to invoke the mtlData class with slightly different arguments.
landsatFACT_LCV.py:
LCV is now invoked with a text file argument which contains the list of tars downloaded by download_landsat_data.php. 
Added exception handler to LCV that allows it to recover to a few known errors including 0 length tar files and fmask failures. LCV "recovers" from these errors by proceeding to the next tar in the runList. I changed the indentation in the main loop to simplify reading the code and to get the python interpreter to realize that I'd added the new try:except: blocks.
download_landsat_data.php:
Added the writing of a downloaded.txt file which contains the list of tar files downloaded during this invocation of download_landsat_data.php. 
lsf_cron.sh:
Passes the downloaded.txt file as argument to landsatFACT_LCV.py.

**Comment by daveism** [comment]
The custom request test in dev failing with permissions issue.

**Comment by daveism** [comment]
pulled after cr worked.  issue related to permissions on extractedTars directory...

**Pull request merged**
